function tri_open()

global tri sbconfig;

if ~isempty(tri)
    try,
        fclose(tri);
    catch
    end
end

tri = serial(sbconfig.tri_com , ...
    'BaudRate',sbconfig.tri_baud,...
    'BytesAvailableFcnMode','byte', ...
    'InputBufferSize',1024, ...
    'OutputBufferSize',1024, ...
    'Terminator', [], ...
    'Timeout',1, ...
    'Tag','tri', ...
    'BytesAvailableFcnCount',9);

   % 'BaudRate', 57600, ...
   
fopen(tri);    % open it

